name: persis_times
description: Astronomical calculations for Islamic prayer times, qibla direction, hijri calendar, and eclipses.
version: 1.0.5
repository: https://github.com/abusabda/PERSIS-TIMES
homepage: https://github.com/abusabda/PERSIS-TIMES

environment:
  sdk: ^3.8.1

dependencies:
  decimal: ^3.2.4

dev_dependencies:
  lints: ^6.1.0
  test: ^1.25.0

license: MIT  